def condiciones_dict():
    """
        Función para almacenar las condiciones para 
        analizar codigos registrales
    """
    # Definiendo un diccionario
    condiciones = dict()
    # Condiciones de nación similares
    condiciones["nacion_similares"] = ["NOMBRE == 'NACION'",
                "NOMBRE == 'LA NACION'",
                "NOMBRE.str.contains('MUNICIPIO DE')",
                "NOMBRE.str.contains('DEPARTAMENTO DE')",
                "NOMBRE.str.contains('INSTITUCION') and NOMBRE.str.contains('DISTRITAL')",
                "NOMBRE.str.contains('ADMINISTRACION PUBLICA AGUAS DE')",
                "NOMBRE.str.contains('ADMINISTRACION PUBLICA')",
                "NOMBRE.str.contains('AEROPUERTO')",
                "NOMBRE.str.contains('AGENCIA DE DESARROLLO')",
                "NOMBRE.str.contains('AGENCIA NACIONAL DE ')",
                "NOMBRE.str.contains('AGENCIA PRESIDENCIAL DE COOPERACION INTERNACIONAL')",
                "NOMBRE.str.contains('AGENCIA COLOMBIANA PARA LA REINTEGRACION DE PERSONAS')",
                "NOMBRE == 'ARMADA NACIONAL'",
                "NOMBRE == 'AGENCIA LOGISTICA DE LAS FUERZAS MILITARES'",
                "NOMBRE == 'AUTORIDAD NACIONAL DE AGRICULTURA Y PESCA'",
                "NOMBRE.str.contains('AUTORIDAD NACIONAL DE')",
                "NOMBRE.str.contains('BAN') and NOMBRE.str.contains('AGRARIO')",
                "NOMBRE.str.contains('BANCO DE COMERCIO EXTERIOR DE COLOMBIA')",
                "NOMBRE.str.contains('DE LA REPUBLICA')",
                "NOMBRE.str.contains('CAJA DE RETIRO DE LAS F')",
                "NOMBRE.str.contains('CAJA PROMOTORA DE VIVIENDA M')",
                "NOMBRE.str.contains('CANAL REGIONAL DE TELEVISION')",
                "NOMBRE.str.contains('CENTRAL DE INVERSIONES')",
                "NOMBRE.str.contains(' CISA ') or NOMBRE == 'CISA'",
                "NOMBRE.str.contains('CENTRALES ELECTRICAS') and NOMBRE.str.contains('NARI')",
                "NOMBRE.str.contains('CENTRALES ELECTRICAS') and NOMBRE.str.contains('CAUCA')",
                "NOMBRE.str.contains('CLUB MILITAR')",
                "NOMBRE.str.contains('COMANDO GENERAL DE')",
                "NOMBRE.str.contains('COMISION DE REGULACION DE')",
                "NOMBRE.str.contains('CORPORACION AUTONOMA REGIONAL DE')",
                "NOMBRE.str.contains('CORPORACION COLOMBIANA INTERNACIONAL')",
                "NOMBRE.str.contains('CORPORACION COLOMBIANA DE INVESTIGACION AGROPECUARIA')",
                "NOMBRE.str.contains('CORPOICA')",
                "NOMBRE.str.contains('CORPORACION DE CIENCIA Y TECNOLOGIA PARA') and NOMBRE.str.contains('NAVAL')",
                "NOMBRE.str.contains('CORPORACION DE') and NOMBRE.str.contains('AERONAUTICA')",
                "NOMBRE.str.contains('CORPORACION NACIONAL PARA LA RECONST')",
                "NOMBRE.str.contains('CORPORACION PARA EL DESARROLLO SOS')",
                "NOMBRE.str.contains('ECOPETROL')",
                "NOMBRE.str.contains('EJER') and NOMBRE.str.contains('NACIO')",
                "NOMBRE.str.contains('ELECTRIFICADORA') and (NOMBRE.str.contains('CAQUETA') or NOMBRE.str.contains('HUILA') or NOMBRE.str.contains('META'))",
                "NOMBRE.str.contains('EMPRESA DE ENERGIA') and (NOMBRE.str.contains('SAN ANDRES') or NOMBRE.str.contains('AMAZONAS'))",
                "NOMBRE.str.contains('EMPRESA DE TELECOMUNICACIONES DE BUCARAMANGA')",
                "NOMBRE.str.contains('EMPRESA DISTRIBUIDORA') and NOMBRE.str.contains('PACIFICO')",
                "NOMBRE.str.contains('FOGANSA')",
                "NOMBRE.str.contains('FONDO GANADERO DE ANTIOQUIA')",
                "NOMBRE == 'FIDUCIARIA COLOMBIANA DE COMERCIO EXTERIOR'",
                "NOMBRE == 'FIDUCIARIA LA PREVISORA'",
                "NOMBRE == 'FINANCIERA DE DESARROLLO NACIONAL'",
                "NOMBRE.str.contains('FINANCIERA') and NOMBRE.str.contains('DESARROLLO') and (NOMBRE.str.contains('NAL') or NOMBRE.str.contains('RIAL'))",
                "NOMBRE.str.contains('FINANCIERA') and NOMBRE.str.contains('DLLO') and (NOMBRE.str.contains('ONAL') or NOMBRE.str.contains('RIAL'))",
                "NOMBRE == 'FINANCIERA DE DESARROLLO TERRITORIAL'",
                "NOMBRE == 'FONDO ADAPTACION'",
                "NOMBRE.str.contains('FONDO GANADERO') and (NOMBRE.str.contains('BOYACA') or NOMBRE.str.contains('ATLANTICO') or NOMBRE.str.contains('CAUCA') or NOMBRE.str.contains('CORDOBA') or NOMBRE.str.contains('CESAR') or NOMBRE.str.contains('HUILA') or NOMBRE.str.contains('MAGDALENA') or NOMBRE.str.contains('META') or NOMBRE.str.contains('TOLIMA'))",
                "NOMBRE.str.contains('FONDO') and NOMBRE.str.contains('FINANC') and NOMBRE.str.contains('AGROPECUARIO')",
                "NOMBRE.str.contains('FONDO') and NOMBRE.str.contains('ROT') and NOMBRE.str.contains('POLI') and NOMBRE.str.contains('NAL')",
                "NOMBRE == 'FUERZA AEREA COLOMBIANA'",
                "NOMBRE == 'FAC'",
                "NOMBRE.str.contains('GENERADORA Y COMERCIALIZADORA DE ENERGIA') and NOMBRE.str.contains('CARIBE')",
                "NOMBRE.str.contains('GESTION ENERGETICA')",
                "NOMBRE == 'INDUSTRIA MILITAR'",
                "NOMBRE == 'INDUMIL'",
                "NOMBRE.str.contains('INSTITUTO AMAZONICO DE INVESTIGACIONES CIENTIFICAS')",
                "NOMBRE.str.contains('INSTITUTO COLOMBIANO AGROPECUARIO')",
                "NOMBRE.str.contains('INSTITUTO COLOMBIANO DE')",
                "NOMBRE.str.contains('INSTITUTO DE HIDROLOGIA')",
                "NOMBRE.str.contains('INSTITUTO DE INVESTIGACION DE RECURSOS BIOLOGICOS ALEX')",
                "NOMBRE.str.contains('INSTITUTO DE INVESTIGACIONES AMBIENTALES DEL PACIFICO')",
                "NOMBRE == 'IAVH'",
                "NOMBRE.str.contains('INSTITUTO DE INVESTIGACIONES MARINAS Y COSTERAS')",
                "NOMBRE.str.contains('INSTITUTO DE PLANIFICACION Y PROMOCION DE SOLUCIONES ENERG')",
                "NOMBRE.str.contains('INSTITUTO GEOGRAFICO AGUSTIN CODAZZI')",
                "NOMBRE == 'IGAC'",
                "NOMBRE.str.contains('INSTITUTO NACIONAL DE')",
                "NOMBRE == 'INVIAS'",
                "NOMBRE.str.contains('INSTITUTO NACIONAL PARA')",
                "NOMBRE.str.contains('INSTITUTO NACIONAL PENI')",
                "NOMBRE.str.contains('INSTITUTO TOLIMENSE DE FORMACION TEC')",
                "NOMBRE.str.contains('INTERCONEXION ELEC')",
                "NOMBRE.str.contains('ISAGEN')",
                "NOMBRE.str.contains('MINISTERIO DE')",
                "NOMBRE.str.contains('PARQUES NACIONALES NATURALES DE COLOMBIA')",
                "NOMBRE.str.contains('PNN')",
                "NOMBRE.str.contains('SERVICIO GEOLOGICO COLOMBIANO')",
                "NOMBRE.str.contains('SERVICIO NACIONAL DE APRENDIZAJE')",
                "NOMBRE == 'SENA'",
                "NOMBRE.str.contains('SOCIEDAD DE ACTIVOS ESPECIALES')",
                "NOMBRE == 'SAE'",
                "NOMBRE.str.contains('SOCIEDAD FIDUCIARIA DE DESARROLLO AGRO')",
                "NOMBRE.str.contains('SUPERINTENDENCIA')",
                "NOMBRE.str.contains('UNIDAD ADMINISTRATIVA ESPECIAL')",
                "NOMBRE.str.contains('UNIDAD DE PLANEACION')",
                "NOMBRE.str.contains('UNIDAD DE PLANIFICACION')",
                "NOMBRE.str.contains('UNIVERSIDAD COLEGIO MAYOR DE CUNDINAMARCA')",
                "NOMBRE.str.contains('UNIVERSIDAD DE CALDAS')",
                "NOMBRE.str.contains('UNIVERSIDAD DE CORDOBA')",
                "NOMBRE.str.contains('UNIVERSIDAD DE LA AMAZONIA')",
                "NOMBRE.str.contains('UNIVERSIDAD DE LOS LLANOS')",
                "NOMBRE.str.contains('UNIVERSIDAD DEL CAUCA')",
                "NOMBRE.str.contains('UNIVERSIDAD DEL PACIFICO')",
                "NOMBRE.str.contains('UNIVERSIDAD MILITAR NUEVA GRANADA')",
                "NOMBRE.str.contains('UNIVERSIDAD NACIONAL ABIERTA Y A DISTANCIA')",
                "NOMBRE.str.contains('UNIVERSIDAD NACIONAL DE COLOMBIA')",
                "NOMBRE.str.contains('UNIVERSIDAD PEDAGOGICA NACIONAL')",
                "NOMBRE.str.contains('UNIVERSIDAD PEDAGOGICA Y TECNOLOGICA DE COLOMBIA')",
                "NOMBRE.str.contains('UNIVERSIDAD POPULAR DEL CESAR')",
                "NOMBRE.str.contains('UNIVERSIDAD SURCOLOMBIANA')",
                "NOMBRE.str.contains('UNIVERSIDAD TECNOLOGICA DE PEREIRA')",
                "NOMBRE.str.contains('UNIVERSIDAD TECNOLOGICA DEL CHOCO DIEGO LUIS CORDOBA')",
                "NOMBRE.str.contains('UNIVERSIDAD') and (NOMBRE.str.contains('ANTIO') or NOMBRE.str.contains('CARTAGENA') or NOMBRE.str.contains('CUNDINAMARCA') or NOMBRE.str.contains('GUAJIRA') or NOMBRE.str.contains('GUAJIRA') or NOMBRE.str.contains('NARI') or NOMBRE.str.contains('PAMPLONA') or NOMBRE.str.contains('SUCRE') or NOMBRE.str.contains('ATLANTICO') or NOMBRE.str.contains('MAGDALENA') or NOMBRE.str.contains('QUINDIO') or NOMBRE.str.contains('TOLIMA') or NOMBRE.str.contains('VALLE') or NOMBRE.str.contains('DISTRITAL'))",
                "NOMBRE.str.contains('ZONA FRANCA ANDINA MANIZALES')",
                "NOMBRE == 'UNAD'",
                "NOMBRE.str.contains('UPTC')",
                "NOMBRE == 'INSTITUTO COLOMBIANO DE DESARROLLO RURAL'",
                "NOMBRE.str.contains('INST') and NOMBRE.str.contains('COL') and NOMBRE.str.contains('DESAR') and NOMBRE.str.contains('RURAL')",
                "NOMBRE == 'ANT'",
                "(NOMBRE.str.contains('DISTRITO') or NOMBRE.str.contains('DISTRITAL')) and (NOMBRE.str.contains('BARRANQUILLA') or NOMBRE.str.contains('BUENAVENTURA') or NOMBRE.str.contains('CARTAGENA') or NOMBRE.str.contains('SANTA MARTA') or NOMBRE.str.contains('RIOHACHA'))",
                "NOMBRE.str.contains('COOPERATIVA AGROPECUARIA') and NOMBRE.str.contains('GINEBRA')",
                "NOMBRE.str.contains('COOPERATIVA') and NOMBRE.str.contains('ENTIDADES') and NOMBRE.str.contains('SALUD') and NOMBRE.str.contains('RISARALDA')",
                "NOMBRE.str.contains('CORPORACION CULTURAL') and NOMBRE.str.contains('MUNIC') and NOMBRE.str.contains('VILLAV')",
                "NOMBRE.str.contains('CORPORACION FORESTAL') and NOMBRE.str.contains('NARIN')",
                "NOMBRE.str.contains('COROPORACION') and NOMBRE.str.contains('NACIONA') and NOMBRE.str.contains('INV') and NOMBRE.str.contains('FORESTAL')",
                "NOMBRE.str.contains('DEPARTAMENTO ADMINISTRATIVO DE')",
                "NOMBRE.str.contains('DEPARTAMENTO') and NOMBRE.str.contains('ADMINISTRATIVO') and NOMBRE.str.contains('AMBIENTE') and NOMBRE.str.contains('BARR')",
                "NOMBRE.str.contains('DIRECCION') and NOMBRE.str.contains('TERRITORIAL') and NOMBRE.str.contains('SALUD') and NOMBRE.str.contains('CALDAS')",
                "NOMBRE.str.contains('E') and NOMBRE.str.contains('CENTRO DE SALUD')",
                "NOMBRE.str.contains('E.S.E') and NOMBRE.str.contains('CENTRO DE SALUD')",
                "NOMBRE.str.contains('I') and NOMBRE.str.contains('CENTRO DE SALUD')",
                "NOMBRE.str.contains('I') and NOMBRE.str.contains('PUESTO') and NOMBRE.str.contains('SALUD')",
                "NOMBRE.str.contains('EMPRESA SOCIAL DEL ESTADO')",
                "NOMBRE.str.contains('ESE HOSPITAL')",
                "NOMBRE.str.contains('E.S.E') and NOMBRE.str.contains('HOSPITAL')",
                "NOMBRE.str.contains('HOSPITAL LOCAL')",
                "NOMBRE.str.contains('HOSPITAL REGIONAL')",
                "NOMBRE.str.contains('E') and NOMBRE.str.contains('AGUAS DE')",
                "NOMBRE.str.contains('EMPRESA') and NOMBRE.str.contains('PUBLIC')",
                "NOMBRE.str.contains('EMSERCOTA')",
                "NOMBRE.str.contains('MUNICIPAL DE SERV')",
                "NOMBRE.str.contains('ACUEDUCTO Y ALCANTARILLADO')",
                "NOMBRE.str.contains('E') and NOMBRE.str.contains('ACUEDUCTO')",
                "NOMBRE.str.contains('AGUAS Y ASEO')",
                "NOMBRE.str.contains('AGUA POTABLE')",
                "NOMBRE.str.contains('EMPRESA DE ENERGIA')",
                "NOMBRE.str.contains('SERVICIOS PUBLICOS')",
                "NOMBRE.str.contains('GOBERNACI')",
                "NOMBRE.str.contains('EMSIRVA')",
                "NOMBRE.str.contains('ENVIASEO')",
                "NOMBRE.str.contains('EPM TELEC')",
                "NOMBRE.str.contains('HIDROELECTRICA PESCAD')",
                "NOMBRE.str.contains('E') and NOMBRE.str.contains('HYDROS')",
                "NOMBRE.str.contains('ALCANTARILLADO Y ASEO')",
                "NOMBRE.str.contains('PLANTA DE TRATAMIENTO')",
                "NOMBRE.str.contains('AGROINDUSTRIAL CASANARE') and NOMBRE.str.contains('LACTEOS')",
                "NOMBRE.str.contains('AGROINDUSTRIAL') and NOMBRE.str.contains('ORIENTE')",
                "NOMBRE.str.contains('AGROPECUARIA') and NOMBRE.str.contains('YONDO')",
                "NOMBRE.str.contains('EMPRESA') and NOMBRE.str.contains('LICORE') and NOMBRE.str.contains('CUNDIN')",
                "NOMBRE.str.contains('EMPRESA') and NOMBRE.str.contains('LICORE') and NOMBRE.str.contains('CAQUET')",
                "NOMBRE.str.contains('OBRAS SANITARIAS DE')",
                "NOMBRE.str.contains('EMPRESA') and NOMBRE.str.contains('LICORE') and NOMBRE.str.contains('NARI')",
                "NOMBRE.str.contains('DEPORT') and NOMBRE.str.contains('MUNICIP')",
                "NOMBRE.str.contains('FONDO') and NOMBRE.str.contains('FOMEN') and (NOMBRE.str.contains('MINER') or NOMBRE.str.contains('AGROPEC'))",
                "NOMBRE.str.contains('INSTIT') and NOMBRE.str.contains('EDUC') and (NOMBRE.str.contains('GUAJIRA') or NOMBRE.str.contains('FLORIDA') or NOMBRE.str.contains('DAGUA') or NOMBRE.str.contains('RURAL') or NOMBRE.str.contains('AGROPEC'))",
                "NOMBRE.str.contains('INST') and NOMBRE.str.contains('CULT') and NOMBRE.str.contains('TURIS')",
                "NOMBRE.str.contains('INST') and NOMBRE.str.contains('DEP') and NOMBRE.str.contains('RECR')",
                "NOMBRE.str.contains('NEPOM')",
                "NOMBRE.str.contains('INDER')",
                "NOMBRE.str.contains('IMDERCUT')",
                "NOMBRE.str.contains('REFORESTADORA INDUSTRIAL') and NOMBRE.str.contains('ANTIOQUIA')",
                "NOMBRE.str.contains('LA NACION')",
                "NOMBRE.str.contains('MUNICIPIO')",
                "NOMBRE.str.contains('VACANTE')",
                "NOMBRE.str.contains('CATASTRAL')",
                "NOMBRE.str.contains('INSTITUTO COLOMBIANO DE')",
                "NOMBRE.str.contains('INCODER')",
                "NOMBRE.str.contains('INCORA')",
                "NOMBRE.str.contains(' ANT ')",
                "NOMBRE.str.contains('AGENCIA NACIONAL DE TIERRAS')",
                "NOMBRE.str.contains('ICBF')",
                "NOMBRE.str.contains('DEPARTAMENTO ')",
                "NOMBRE.str.contains(' SAE ')",
                "NOMBRE.str.contains('SOCIEDAD DE ACTIVOS ESPECIALES')",
                "NOMBRE.str.contains('INVIAS')",
                "NOMBRE.str.contains('INSTITUTO NACIONAL DE')",
                "NOMBRE.str.contains('DESARROLLO RURAL')",
                "NOMBRE.str.contains('MINISTERIO')",
                "(NOMBRE.str.contains('INSTITUTO') or NOMBRE.str.contains('INSTITUCION')) and NOMBRE.str.contains('DISTRITAL')",
                "NOMBRE.str.contains('SECRETARIA DE OBRAS PUBLICAS')",
                "NOMBRE == 'BANCO DE TIERRAS DEL MUNICIPIO'",
                "NOMBRE == 'DEPARTAMENTO'",
                "NOMBRE.str.contains('ADUANA')",
                "NOMBRE.str.contains('AGRARIA')",
                "NOMBRE.str.contains('ALCALDIA')",
                "NOMBRE.str.contains('VIVIENDA MILITAR')",
                "NOMBRE.str.contains('BANC') and NOMBRE.str.contains('CENTR') and NOMBRE.str.contains('HIPOTE')",
                "NOMBRE.str.contains('AHORRO')",
                "NOMBRE.str.contains('BOMBERO')",
                "NOMBRE.str.contains('COMIT') and NOMBRE.str.contains('DEPARTA')",
                "NOMBRE.str.contains('COMIT') and NOMBRE.str.contains('JUSTICI')",
                "NOMBRE.str.contains('COMIT') and NOMBRE.str.contains('MUNICI')",
                "NOMBRE.str.contains('CONTRALOR')",
                "NOMBRE == 'DIAN'",
                "NOMBRE.str.contains('D.I.A.N') or NOMBRE.str.contains(' DIAN ')",
                "NOMBRE.str.contains('DIREC') and NOMBRE.str.contains('NAC')",
                "NOMBRE.str.contains('DIREC') and NOMBRE.str.contains('GEN')",
                "NOMBRE.str.contains('EDUC') and NOMBRE.str.contains('NACIO')",
                "NOMBRE.str.contains('EMPRESA COLOMBIANA')",
                "NOMBRE.str.contains('FEDE') and NOMBRE.str.contains('NACI')",
                "NOMBRE.str.contains('FISCALIA')",
                "NOMBRE.str.contains('FONDO') and NOMBRE.str.contains('NACIO')",
                "NOMBRE.str.contains('DIR') and NOMBRE.str.contains('IMPU') and NOMBRE.str.contains('ADU')",
                "NOMBRE.str.contains('INSCREDIAL')",
                "NOMBRE.str.contains('INSTI') and NOMBRE.str.contains('CREDI')",
                "NOMBRE.str.contains('INSTI') and NOMBRE.str.contains('GEO')",
                "NOMBRE.str.contains('INSTI') and NOMBRE.str.contains('NACI')",
                "NOMBRE.str.contains('INURBE')",
                "NOMBRE.str.contains('JUZGADO')",
                "NOMBRE.str.contains('MUNICIPAL')",
                "NOMBRE.str.contains('OBRA') and NOMBRE.str.contains('PUBLIC')",
                "NOMBRE.str.contains('POLICIA')",
                "NOMBRE.str.contains('REGISTRADU')",
                "NOMBRE.str.contains('SENA') and NOMBRE.str.contains('SERV') and NOMBRE.str.contains('NAC')",
                "NOMBRE.str.contains('TESORERIA')",
                "NOMBRE.str.contains('UNIDA') and NOMBRE.str.contains('TIERRA')",
                "NOMBRE.str.contains('TRIBUNAL')",
                "NOMBRE.str.contains('NACION LA')",
                "NOMBRE.str.contains('TELEVI') and NOMBRE.str.contains('NAC')",
                "NOMBRE.str.contains('GOB') and NOMBRE.str.contains('NAC')",
                "NOMBRE.str.contains('TELECOM')",
                "NOMBRE.str.contains('INRAVISION')",
                "NOMBRE.str.contains('FERRO') and NOMBRE.str.contains('NAC')",
                "NOMBRE.str.contains('SERV') and NOMBRE.str.contains('NAC') and NOMBRE.str.contains('APRE')",
                "NOMBRE.str.contains('INVISAN')",
                "NOMBRE.str.contains('INST') and NOMBRE.str.contains('DIST')",
                "NOMBRE.str.contains('INDERENA')",
                "NOMBRE.str.contains('INDUNAL')",
                "NOMBRE.str.contains('INDU') and NOMBRE.str.contains('NAC') and NOMBRE.str.contains('ALI')",
                "NOMBRE.str.contains('C V C CORPORACION AUTONOMA REGION')",
                "NOMBRE.str.contains('CORPORACION AUTONOMA REGIONAL')",
                "NOMBRE.str.contains('CORPORACION AUTONOMA REGION')",
                "NOMBRE.str.contains('ANT AGENCIA NACIONAL DE TIERRA')",
                "NOMBRE.str.contains('INSTITUCION EDUCATIVA')",
                "NOMBRE.str.contains('CAJA DE CREDITO AGRARIO')",
                "NOMBRE.str.contains('MUNICIPO')",
                "NOMBRE.str.contains('DEPARTAMENTO DE')"
            ]
    # Condiciones regla 1 paso 1
    condiciones["r1p1"] = [
                    "ESPECIFICACION.str.contains('ADJUD') and ESPECIFICACION.str.contains('BALD') and ESPECIFICACION.str.contains('REVOCA')== False",
                    "ESPECIFICACION.str.contains('ADJUD') and ESPECIFICACION.str.contains('VACAN')",
                    "ESPECIFICACION.str.contains('ADJUD') and ESPECIFICACION.str.contains('AGRIC') and ESPECIFICACION.str.contains('FAMI')"
                ]
    # Condiciones regla 1, regla 2 y regla 12 paso 2
    condiciones["r1p2"] =[
                    "ESPECIFICACION.str.contains('ADJUD') and ESPECIFICACION.str.contains('EXPROP')",
                    "ESPECIFICACION.str.contains('EXPROP') and ESPECIFICACION.str.contains('ADMIN')",
                    "ESPECIFICACION.str.contains('EXPROP') and ESPECIFICACION.str.contains('JUDI')",
                    "(ESPECIFICACION.str.contains('EXTINC') or ESPECIFICACION.str.contains('ESTINC')) and ESPECIFICACION.str.contains('DOMIN')",
                    "ESPECIFICACION.str.contains('REVERS') and ESPECIFICACION.str.contains('BALD')",
                    "ESPECIFICACION.str.contains('REVOCA') and ESPECIFICACION.str.contains('ADMIN')",
                    "ESPECIFICACION.str.contains('REVOCA') and ESPECIFICACION.str.contains('JUDI')",
                    "ESPECIFICACION.str.contains('DECLARA') and ESPECIFICACION.str.contains('SANEA') and ESPECIFICACION.str.contains('AUTOMA')"
                ]
    # Condiciones regla 2 y regla 3 paso 1
    condiciones["r2p1"] = [
                    "ESPECIFICACION.str.contains('COMPRAVENTA') and ESPECIFICACION.str.contains('MODO') and ESPECIFICACION.str.contains('ADQUISICI')",
                    "ESPECIFICACION.str.contains('PERMUTA') and ESPECIFICACION.str.contains('MODO') and ESPECIFICACION.str.contains('ADQUISICI')",
                    "ESPECIFICACION.str.contains('DONACI') and ESPECIFICACION.str.contains('MODO') and ESPECIFICACION.str.contains('ADQUISICI')",
                    "ESPECIFICACION == 'COMPRAVENTA' or ESPECIFICACION == 'VENTA' or ESPECIFICACION == 'PERMUTA' or ESPECIFICACION == 'DONACION'",
                    "ESPECIFICACION.str.contains('ACCESI') and ESPECIFICACION.str.contains('SUELO')",
                    "ESPECIFICACION.str.contains('ENTREGA') and ESPECIFICACION.str.contains('INMUEBLE') and ESPECIFICACION.str.contains('ENTIDAD')",
                    "ESPECIFICACION.str.contains('ADJUD') and ESPECIFICACION.str.contains('HIPOTECA')",
                    "ESPECIFICACION.str.contains('ADJUD') and ESPECIFICACION.str.contains('REMATE')",
                    "ESPECIFICACION.str.contains('ADJUD') and ESPECIFICACION.str.contains('SUCESI')",
                    "ESPECIFICACION.str.contains('ADJUD') and ESPECIFICACION.str.contains('LIQUIDACI') and ESPECIFICACION.str.contains('COMUNIDAD')",
                    "ESPECIFICACION.str.contains('ADJUD') and ESPECIFICACION.str.contains('LIQUIDACI') and ESPECIFICACION.str.contains('COMERCIAL')",
                    "ESPECIFICACION.str.contains('ADJUD') and ESPECIFICACION.str.contains('LIQUIDACI') and ESPECIFICACION.str.contains('CONYUGAL')",
                    "ESPECIFICACION.str.contains('ADJUD') and ESPECIFICACION.str.contains('LIQUIDACI') and ESPECIFICACION.str.contains('PATRIMONI')",
                    "ESPECIFICACION.str.contains('ADJUD') and ESPECIFICACION.str.contains('SUCESI') and ESPECIFICACION.str.contains('PARTICI')",
                    "ESPECIFICACION.str.contains('CESI') and ESPECIFICACION.str.contains('GRATUITO') and ESPECIFICACION.str.contains('FISCAL')",
                    "ESPECIFICACION.str.contains('COMPRAVENTA') and ESPECIFICACION.str.contains('PARCIAL')",
                    "ESPECIFICACION.str.contains('CONSOLIDA') and ESPECIFICACION.str.contains('DOMINIO') and ESPECIFICACION.str.contains('PLENO')",
                    "ESPECIFICACION.str.contains('DONACI') and ESPECIFICACION.str.contains('PAGO')",
                    "ESPECIFICACION.str.contains('DECLARA') and ESPECIFICACION.str.contains('PERTENENCIA')",
                    "ESPECIFICACION.str.contains('PRESCRIPCI') and ESPECIFICACION.str.contains('AGRARIA')",
                    "ESPECIFICACION.str.contains('RECUPERA') and ESPECIFICACION.str.contains('TITULAR') and ESPECIFICACION.str.contains('EXPROPIA')",
                    "ESPECIFICACION.str.contains('TRANSACCION')",
                    "ESPECIFICACION.str.contains('ADJUD') and ESPECIFICACION.str.contains('LIQUIDA') and ESPECIFICACION.str.contains('SOCIEDAD') and ESPECIFICACION.str.contains('HECHO')",
                    "ESPECIFICACION.str.contains('SANEAMIENTO') and ESPECIFICACION.str.contains('1561')",
                    "ESPECIFICACION.str.contains('ADJUD') and ESPECIFICACION.str.contains('LIQUIDA') and ESPECIFICACION.str.contains('1116')",
                    "ESPECIFICACION.str.contains('RESTITUC') and ESPECIFICACION.str.contains('DOMINIO') and ESPECIFICACION.str.contains('1448')",
                    "ESPECIFICACION.str.contains('DOMINIO') and ESPECIFICACION.str.contains('COMPENSA')",
                    "ESPECIFICACION.str.contains('REASENTAMIENTO')",
                    "ESPECIFICACION.str.contains('SANEAMIENTO') and ESPECIFICACION.str.contains('FALSA')",
                    "ESPECIFICACION.str.contains('TRANSFEREN') and ESPECIFICACION.str.contains('CESI')"                    
                ]
    # Condiciones regla 3 paso 2
    condiciones["r3p2"] =[
                    "ESPECIFICACION.str.contains('POSESI') and ESPECIFICACION.str.contains('EFECTIVA')",
                    "ESPECIFICACION.str.contains('AFECTA') and ESPECIFICACION.str.contains('MEJORA')",
                    "ESPECIFICACION.str.contains('COMPRAVENTA') and ESPECIFICACION.str.contains('AJENA')",
                    "ESPECIFICACION.str.contains('COMPRAVENTA') and ESPECIFICACION.str.contains('ACCI')",
                    "ESPECIFICACION.str.contains('COMPRAVENTA') and ESPECIFICACION.str.contains('GANANCIAL')",
                    "ESPECIFICACION.str.contains('COMPRAVENTA') and ESPECIFICACION.str.contains('POSESI')",
                    "ESPECIFICACION.str.contains('COMPRAVENTA') and ESPECIFICACION.str.contains('MEJORA')",
                    "ESPECIFICACION.str.contains('DONACI') and ESPECIFICACION.str.contains('ACCI')",
                    "ESPECIFICACION.str.contains('DONACI') and ESPECIFICACION.str.contains('GANANCIAL')",
                    "ESPECIFICACION.str.contains('PATRIMONIO') and ESPECIFICACION.str.contains('MEJORA')",
                    "ESPECIFICACION.str.contains('TRANSFEREN') and ESPECIFICACION.str.contains('POSESI')",
                    "ESPECIFICACION.str.contains('DECLARA') and ESPECIFICACION.str.contains('POSESI')",
                    "ESPECIFICACION.str.contains('RESTITUCI') and ESPECIFICACION.str.contains('POSE')"
                ]
    # Condiciones regla 4 paso 1
    condiciones["r4p1"] = [
                    "ESPECIFICACION.str.contains('ACCESI') and ESPECIFICACION.str.contains('SUELO')",
                    "ESPECIFICACION.str.contains('ENTREGA') and ESPECIFICACION.str.contains('INMUEBLE') and ESPECIFICACION.str.contains('ENTIDAD')",
                    "ESPECIFICACION.str.contains('ADJUD') and ESPECIFICACION.str.contains('HIPOTECA')",
                    "ESPECIFICACION.str.contains('ADJUD') and ESPECIFICACION.str.contains('REMATE')",
                    "ESPECIFICACION.str.contains('ADJUD') and ESPECIFICACION.str.contains('SUCESI')",
                    "ESPECIFICACION.str.contains('ADJUD') and ESPECIFICACION.str.contains('LIQUIDACI') and ESPECIFICACION.str.contains('COMUNIDAD')",
                    "ESPECIFICACION.str.contains('ADJUD') and ESPECIFICACION.str.contains('LIQUIDACI') and ESPECIFICACION.str.contains('COMERCIAL')",
                    "ESPECIFICACION.str.contains('ADJUD') and ESPECIFICACION.str.contains('LIQUIDACI') and ESPECIFICACION.str.contains('CONYUGAL')",
                    "ESPECIFICACION.str.contains('ADJUD') and ESPECIFICACION.str.contains('LIQUIDACI') and ESPECIFICACION.str.contains('PATRIMONI')",
                    "ESPECIFICACION.str.contains('ADJUD') and ESPECIFICACION.str.contains('SUCESI') and ESPECIFICACION.str.contains('PARTICI')",
                    "ESPECIFICACION.str.contains('CESI') and ESPECIFICACION.str.contains('GRATUITO') and ESPECIFICACION.str.contains('FISCAL')",
                    "ESPECIFICACION.str.contains('COMPRAVENTA') and ESPECIFICACION.str.contains('PARCIAL')",
                    "ESPECIFICACION.str.contains('CONSOLIDA') and ESPECIFICACION.str.contains('DOMINIO') and ESPECIFICACION.str.contains('PLENO')",
                    "ESPECIFICACION.str.contains('DONACI') and ESPECIFICACION.str.contains('PAGO')",
                    "ESPECIFICACION.str.contains('DECLARA') and ESPECIFICACION.str.contains('PERTENENCIA')",
                    "ESPECIFICACION.str.contains('PRESCRIPCI') and ESPECIFICACION.str.contains('AGRARIA')",
                    "ESPECIFICACION.str.contains('RECUPERA') and ESPECIFICACION.str.contains('TITULAR') and ESPECIFICACION.str.contains('EXPROPIA')",
                    "ESPECIFICACION.str.contains('TRANSACCION')",
                    "ESPECIFICACION.str.contains('ADJUD') and ESPECIFICACION.str.contains('LIQUIDA') and ESPECIFICACION.str.contains('SOCIEDAD') and ESPECIFICACION.str.contains('HECHO')",
                    "ESPECIFICACION.str.contains('SANEAMIENTO') and ESPECIFICACION.str.contains('1561')",
                    "ESPECIFICACION.str.contains('ADJUD') and ESPECIFICACION.str.contains('LIQUIDA') and ESPECIFICACION.str.contains('1116')",
                    "ESPECIFICACION.str.contains('RESTITUC') and ESPECIFICACION.str.contains('DOMINIO') and ESPECIFICACION.str.contains('1448')",
                    "ESPECIFICACION.str.contains('DOMINIO') and ESPECIFICACION.str.contains('COMPENSA')",
                    "ESPECIFICACION.str.contains('REASENTAMIENTO')",
                    "ESPECIFICACION.str.contains('SANEAMIENTO') and ESPECIFICACION.str.contains('FALSA')",
                    "ESPECIFICACION.str.contains('TRANSFEREN') and ESPECIFICACION.str.contains('CESI')"                    
                ]
    # Regla 4 Paso 2 Condición 1
    condiciones["r4p2c1"] = [
                    "COMPLEMENTACION.str.contains('LIBRO') and COMPLEMENTACION.str.contains('PRIMERO')",
                    "COMPLEMENTACION.str.contains('LIBRO') and COMPLEMENTACION.str.contains('1')",
                    "COMPLEMENTACION.str.contains('LIBRO1')",
                    "COMPLEMENTACION.str.contains('LIBRO') and COMPLEMENTACION.str.contains('01')",
                    "COMPLEMENTACION.str.contains('LIBRO01')",
                    "COMPLEMENTACION.str.contains('L') and COMPLEMENTACION.str.contains('1')",
                    "COMPLEMENTACION.str.contains('L1')"
                    ]
    # Regla 5 Paso 1
    condiciones["r5p1"] = [
                    "ESPECIFICACION.str.contains('POSESI') and ESPECIFICACION.str.contains('EFECTIVA')",
                    "ESPECIFICACION.str.contains('ADJUD') and ESPECIFICACION.str.contains('ACCI')",
                    "ESPECIFICACION.str.contains('ADJUD') and ESPECIFICACION.str.contains('GANANCIAL')",
                    "ESPECIFICACION.str.contains('AFECTA') and ESPECIFICACION.str.contains('MEJORA')",
                    "ESPECIFICACION.str.contains('COMPRAVENTA') and ESPECIFICACION.str.contains('AJENA')",
                    "ESPECIFICACION.str.contains('TRANSFEREN') and ESPECIFICACION.str.contains('CUERPO')",
                    "ESPECIFICACION.str.contains('COMPRAVENTA') and ESPECIFICACION.str.contains('GANANCIAL')",
                    "ESPECIFICACION.str.contains('COMPRAVENTA') and ESPECIFICACION.str.contains('ACCI')",
                    "ESPECIFICACION.str.contains('COMPRAVENTA') and ESPECIFICACION.str.contains('POSESI')",
                    "ESPECIFICACION.str.contains('DECLARA') and ESPECIFICACION.str.contains('MEJORA')",
                    "ESPECIFICACION.str.contains('DONACI') and ESPECIFICACION.str.contains('ACCI')",
                    "ESPECIFICACION.str.contains('DONACI') and ESPECIFICACION.str.contains('GANANCIAL')",
                    "ESPECIFICACION.str.contains('PATRIMONIO') and ESPECIFICACION.str.contains('MEJORA')",
                    "ESPECIFICACION.str.contains('REMATE') and ESPECIFICACION.str.contains('ACCI')",
                    "ESPECIFICACION.str.contains('REMATE') and ESPECIFICACION.str.contains('GANANCIAL')",
                    "ESPECIFICACION.str.contains('COMPRAVENTA') and ESPECIFICACION.str.contains('MEJORA')",
                    "ESPECIFICACION.str.contains('TRANSFEREN') and ESPECIFICACION.str.contains('POSESI')",
                    "ESPECIFICACION.str.contains('DACION') and ESPECIFICACION.str.contains('ACCI')",
                    "ESPECIFICACION.str.contains('DECLARA') and ESPECIFICACION.str.contains('POSESI')",
                    "ESPECIFICACION.str.contains('PERMUTA') and ESPECIFICACION.str.contains('ACCI')"
                    ]
    # Regla 5 Paso 2
    condiciones["r5p2"] = [
                        "ESPECIFICACION.str.contains('ADJUD') and ESPECIFICACION.str.contains('BALDI')",
                        "ESPECIFICACION.str.contains('ADJUD') and ESPECIFICACION.str.contains('VACAN')",
                        "ESPECIFICACION.str.contains('ADJUD') and ESPECIFICACION.str.contains('AGRICOLA') and ESPECIFICACION.str.contains('FAMI')"
                        ]
    # Regla 7 paso 1
    condiciones["r7p1"] = [
                        "ESPECIFICACION.str.contains('AMPLIA') and  ESPECIFICACION.str.contains('HIPOTECA')",
                        "ESPECIFICACION.str.contains('MOBILIZACI')",
                        "ESPECIFICACION.str.contains('HIPOTECA') and ESPECIFICACION.str.contains('ABIERTA')",
                        "ESPECIFICACION.str.contains('HIPOTECA') and ESPECIFICACION.str.contains('INDETER')",
                        "ESPECIFICACION.str.contains('HIPOTECA') and ESPECIFICACION.str.contains('USUFRUCTO')",
                        "ESPECIFICACION.str.contains('HIPOTECA') and ESPECIFICACION.str.contains('DERECH') and ESPECIFICACION.str.contains('ACCI')",
                        "ESPECIFICACION.str.contains('HIPOTECA') and ESPECIFICACION.str.contains('GANAN')",
                        "ESPECIFICACION.str.contains('HIPOTECA') and ESPECIFICACION.str.contains('ANTECEDENTE')",
                        "ESPECIFICACION.str.contains('HIPOTECA') and ESPECIFICACION.str.contains('AGRICO')",
                        "ESPECIFICACION.str.contains('HIPOTECA') and ESPECIFICACION.str.contains('CUOTA')",
                        "ESPECIFICACION.str.contains('HIPOTECA') and ESPECIFICACION.str.contains('NUDA')",
                        "ESPECIFICACION.str.contains('PLUSVALIA')",
                        "ESPECIFICACION.str.contains('ACREEDOR') and ESPECIFICACION.str.contains('HIPOTECA')",
                        "ESPECIFICACION.str.contains('BENEFICIO') and ESPECIFICACION.str.contains('SEPARA')",
                        "ESPECIFICACION.str.contains('RATIFICA') and ESPECIFICACION.str.contains('HIPOTECA')",
                        "ESPECIFICACION == 'VALORIZACION'"
                        ]
    # Regla 8 paso 1
    condiciones["r8p1"] = [
                        "ESPECIFICACION.str.contains('ADJUD') and  ESPECIFICACION.str.contains('CUOTA')",
                        "ESPECIFICACION.str.contains('ADJUD') and ESPECIFICACION.str.contains('NUDA')",
                        "ESPECIFICACION == 'SUBSUELO'",
                        "ESPECIFICACION == 'COPROPIEDAD'",
                        "ESPECIFICACION.str.contains('COMPRAVENTA') and ESPECIFICACION.str.contains('CUOTA')",
                        "ESPECIFICACION.str.contains('COMPRAVENTA') and ESPECIFICACION.str.contains('NUDA')",
                        "ESPECIFICACION.str.contains('COMPRAVENTA') and ESPECIFICACION.str.contains('USUFRUCTO')",
                        "ESPECIFICACION.str.contains('CONSTITU') and ESPECIFICACION.str.contains('FIDEICOMISO')",
                        "ESPECIFICACION.str.contains('CONSTITU') and ESPECIFICACION.str.contains('USUFRUCTO')",
                        "ESPECIFICACION.str.contains('CONSTITU') and ESPECIFICACION.str.contains('CONDOMINIO')",
                        "ESPECIFICACION.str.contains('CONSTITU') and  ESPECIFICACION.str.contains('HORIZONTAL')",
                        "ESPECIFICACION.str.contains('DERECHO') and ESPECIFICACION.str.contains('HABITA')",
                        "ESPECIFICACION.str.contains('DERECHO') and ESPECIFICACION.str.contains('USO')",
                        "ESPECIFICACION.str.contains('DONACI') and ESPECIFICACION.str.contains('NUDA')",
                        "ESPECIFICACION.str.contains('DONACI') and ESPECIFICACION.str.contains('USUFRUCTO')",
                        "ESPECIFICACION.str.contains('REMATE') and ESPECIFICACION.str.contains('CUOTA')",
                        "ESPECIFICACION.str.contains('RESERVA') and ESPECIFICACION.str.contains('USUFRUCTO')",
                        "ESPECIFICACION.str.contains('DACION') and ESPECIFICACION.str.contains('CUOTA')",
                        "ESPECIFICACION.str.contains('DONACI') and ESPECIFICACION.str.contains('CUOTA')",
                        "ESPECIFICACION.str.contains('PERMUTA') and ESPECIFICACION.str.contains('CUOTA')",
                        "ESPECIFICACION.str.contains('ADJUD') and ESPECIFICACION.str.contains('USUFRUCTO')",
                        "ESPECIFICACION.str.contains('REMATE') and ESPECIFICACION.str.contains('NUDA')",
                        "ESPECIFICACION.str.contains('REMATE') and ESPECIFICACION.str.contains('USUFRUCTO')",
                        "ESPECIFICACION.str.contains('CONYUGAL') and ESPECIFICACION.str.contains('USUFRUCTO')",
                        "ESPECIFICACION.str.contains('ACRECIMIENTO') and ESPECIFICACION.str.contains('USUFRUCTO')"
                        ]
    # Regla 9 paso 1
    condiciones["r9p1"] = [
                        "ESPECIFICACION.str.contains('SERVIDUMBRE') and ESPECIFICACION.str.contains('ACUEDUCTO')",
                        "ESPECIFICACION.str.contains('SERVIDUMBRE') and ESPECIFICACION.str.contains('AGUA')",
                        "ESPECIFICACION.str.contains('SERVIDUMBRE') and ESPECIFICACION.str.contains('AIRE')",
                        "ESPECIFICACION.str.contains('SERVIDUMBRE') and ESPECIFICACION.str.contains('ENERGIA')",
                        "ESPECIFICACION.str.contains('SERVIDUMBRE') and ESPECIFICACION.str.contains('GASODUCTO')",
                        "ESPECIFICACION.str.contains('SERVIDUMBRE') and ESPECIFICACION.str.contains('LUZ')",
                        "ESPECIFICACION.str.contains('SERVIDUMBRE') and ESPECIFICACION.str.contains('OLEODUCTO')",
                        "ESPECIFICACION.str.contains('SERVIDUMBRE') and ESPECIFICACION.str.contains('TRANSITO')",
                        "ESPECIFICACION.str.contains('SERVIDUMBRE') and ESPECIFICACION.str.contains('MINERA')",
                        "ESPECIFICACION.str.contains('SERVIDUMBRE') and ESPECIFICACION.str.contains('HIDROCARBUROS')",
                        "ESPECIFICACION.str.contains('SERVIDUMBRE') and ESPECIFICACION.str.contains('CATENARIA')",
                        "ESPECIFICACION.str.contains('SERVIDUMBRE') and ESPECIFICACION.str.contains('ALCANTARILLADO')"
                        ]
    # Regla 10 paso 1
    condiciones["r10p1"] = [
                        "ESPECIFICACION.str.contains('DESLINDE') and ESPECIFICACION.str.contains('AMOJONAMIENTO')",
                        "ESPECIFICACION.str.contains('DIVISI') and ESPECIFICACION.str.contains('MATERIAL')",
                        "ESPECIFICACION.str.contains('DESENGLOBE')",
                        "ESPECIFICACION.str.contains('ENGLOBE')",
                        "ESPECIFICACION.str.contains('LOTEO')",
                        "ESPECIFICACION.str.contains('RELOTEO')",
                        "ESPECIFICACION.str.contains('CONSTITU') and ESPECIFICACION.str.contains('PARCELA')"
                        ]
    # Regla 11 paso 1
    condiciones["r11p1"] = [
                        "ESPECIFICACION == 'ACLARACION'",
                        "ESPECIFICACION.str.contains('CORRECCI') and ESPECIFICACION.str.contains('LINDERO')",
                        "ESPECIFICACION == 'ACTUALIZACION'",
                        "ESPECIFICACION == 'NOMBRE'"
                        ]
    # Regla 12 paso 1
    condiciones["r12p1"] = [
                        "ESPECIFICACION.str.contains('SALIO') and ESPECIFICACION.str.contains('NACION')",
                        "ESPECIFICACION.str.contains('DERECHO') and ESPECIFICACION.str.contains('1974')"       
                        ]
    # Regla 13 paso 1
    condiciones["r13p1"] = [
                        "ESPECIFICACION == 'DEMANDA'",
                        "ESPECIFICACION == 'EMBARGO'",
                        "ESPECIFICACION.str.contains('COMISO') and ESPECIFICACION.str.contains('ESPECIAL')",
                        "ESPECIFICACION.str.contains('DECLARACION') and ESPECIFICACION.str.contains('GARANTE')",
                        "ESPECIFICACION.str.contains('DECLARATORIA') and ESPECIFICACION.str.contains('SOCIAL')",
                        "ESPECIFICACION.str.contains('DECLARATORIA') and ESPECIFICACION.str.contains('UTILIDAD')",
                        "ESPECIFICACION.str.contains('DECOMISO') and ESPECIFICACION.str.contains('BIENES')",
                        "ESPECIFICACION.str.contains('DERECHO') and ESPECIFICACION.str.contains('PREFERENCIA')",
                        "ESPECIFICACION.str.contains('INICIACION') and ESPECIFICACION.str.contains('ENAJENACION')",
                        "ESPECIFICACION.str.contains('ADMINISTRATIVAS') and ESPECIFICACION.str.contains('CLARIFICACION')",
                        "ESPECIFICACION.str.contains('PROCEDIMIENTO') and ESPECIFICACION.str.contains('EXPROPIACION')",
                        "ESPECIFICACION.str.contains('INICIACION') and ESPECIFICACION.str.contains('ADQUISICION')",
                        "ESPECIFICACION.str.contains('OFERTA') and ESPECIFICACION.str.contains('URBANO')",
                        "ESPECIFICACION.str.contains('PROHIBICION') and ESPECIFICACION.str.contains('ADMINISTRATIVA')",
                        "ESPECIFICACION.str.contains('PROHIBICION') and ESPECIFICACION.str.contains('GRAVÁMENES')",
                        "ESPECIFICACION.str.contains('PROHIBICION') and ESPECIFICACION.str.contains('ENAJENAR')",
                        "ESPECIFICACION.str.contains('PROHIBICION') and ESPECIFICACION.str.contains('GRAVAR')",
                        "ESPECIFICACION.str.contains('PROHIBICION') and ESPECIFICACION.str.contains('INSCRIPCION')",
                        "ESPECIFICACION.str.contains('PROHIBICION') and ESPECIFICACION.str.contains('JUDICIAL')",
                        "ESPECIFICACION.str.contains('PROHIBICION') and ESPECIFICACION.str.contains('REGISTRO')",
                        "ESPECIFICACION == 'SUSPENSION'",
                        "ESPECIFICACION.str.contains('TOMA') and ESPECIFICACION.str.contains('POSESION')",
                        "ESPECIFICACION.str.contains('ABSTENERSE') and ESPECIFICACION.str.contains('ENAJENACIONES')",
                        "ESPECIFICACION.str.contains('LIBRE') and ESPECIFICACION.str.contains('DOMINIO')",
                        "ESPECIFICACION.str.contains('DENUNCIA') and ESPECIFICACION.str.contains('DESPLAZAMIENTO')",
                        "ESPECIFICACION.str.contains('INICIO') and ESPECIFICACION.str.contains('LIQUIDACION')",
                        "ESPECIFICACION.str.contains('ADMISION') and ESPECIFICACION.str.contains('RESTITUCION')",
                        "ESPECIFICACION.str.contains('SUSTRACCION') and ESPECIFICACION.str.contains('1448')",
                        "ESPECIFICACION.str.contains('LIQUIDACION') and ESPECIFICACION.str.contains('ADMINISTRATIVA')",
                        "ESPECIFICACION.str.contains('LIQUIDACION') and ESPECIFICACION.str.contains('REVISION')",
                        "ESPECIFICACION.str.contains('PROTECCION') and ESPECIFICACION.str.contains('DOMICILIO')",
                        "ESPECIFICACION.str.contains('INICIO') and ESPECIFICACION.str.contains('REORGANIZACION')",
                        "ESPECIFICACION.str.contains('SUSPENSION') and ESPECIFICACION.str.contains('DISPOSITIVO')",
                        "ESPECIFICACION.str.contains('PROTECCION') and ESPECIFICACION.str.contains('JURIDICA')",
                        "ESPECIFICACION.str.contains('CAUTELAR') and ESPECIFICACION.str.contains('NEGOCIOS')"
                    ]
    # Regla 14 paso 1
    condiciones["r14p1"] = [
                        "ESPECIFICACION.str.contains('CANCELA') and ESPECIFICACION.str.contains('JUDICIAL')",
                        "ESPECIFICACION.str.contains('CANCELA') and ESPECIFICACION.str.contains('PROVIDENCIA')",
                        "ESPECIFICACION.str.contains('CANCELA') and ESPECIFICACION.str.contains('PARTES')",
                        "ESPECIFICACION.str.contains('CANCELA') and ESPECIFICACION.str.contains('PARCIAL')",
                        "ESPECIFICACION.str.contains('CANCELA') and ESPECIFICACION.str.contains('MANDATO')"
                    ]

    
    return condiciones